services:
  api:
    build:
      context: .
      dockerfile: storage/dockerfiles/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase?schema=public"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
